<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<div class="wrap">
    <h1>Заявка #<?php echo $booking ? (int) $booking['id'] : 0; ?></h1>
    <?php if ( ! $booking ) : ?><p>Заявку не знайдено.</p></div><?php return; endif; ?>
    <div class="ucu-admin-grid">
        <div class="ucu-admin-panel"><h2>Основні дані</h2><p><strong>ПІБ:</strong> <?php echo esc_html( trim( $booking['last_name'] . ' ' . $booking['first_name'] . ' ' . $booking['middle_name'] ) ); ?></p><p><strong>Email:</strong> <?php echo esc_html( $booking['email'] ); ?></p><p><strong>Телефон:</strong> <?php echo esc_html( $booking['phone'] ); ?></p><p><strong>Status:</strong> <?php echo esc_html( $booking['status'] ); ?></p><p><strong>Current:</strong> <?php echo (int) $booking['is_current']; ?></p></div>
        <div class="ucu-admin-panel"><h2>Слот та інтеграції</h2><p><strong>Слот:</strong> <?php echo $slot ? esc_html( $slot['slot_date'] . ' ' . substr( $slot['start_time'], 0, 5 ) . '-' . substr( $slot['end_time'], 0, 5 ) ) : '—'; ?></p><p><strong>Meet:</strong> <?php echo $booking['meet_link'] ? '<a href="' . esc_url( $booking['meet_link'] ) . '" target="_blank" rel="noopener">' . esc_html( $booking['meet_link'] ) . '</a>' : '—'; ?></p><p><strong>Calendar event ID:</strong> <?php echo esc_html( $booking['calendar_event_id'] ?: '—' ); ?></p><p><strong>Sheet row ID:</strong> <?php echo esc_html( $booking['sheet_row_id'] ?: '—' ); ?></p><?php if ( $booking['error_message'] ) : ?><p class="ucu-error-text"><strong>Error:</strong> <?php echo esc_html( $booking['error_message'] ); ?></p><?php endif; ?></div>
        <div class="ucu-admin-panel"><h2>Фото</h2><?php if ( $booking['photo_attachment_id'] ) : ?><?php echo wp_get_attachment_image( (int) $booking['photo_attachment_id'], 'medium' ); ?><p><a href="<?php echo esc_url( wp_get_attachment_url( (int) $booking['photo_attachment_id'] ) ); ?>" target="_blank" rel="noopener">Відкрити файл</a></p><?php else : ?><p>Фото немає.</p><?php endif; ?></div>
        <div class="ucu-admin-panel"><h2>Оцінки</h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="scores"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><p>Auto: <?php echo esc_html( $booking['auto_score'] ); ?></p><p><label>Manual <input type="number" step="0.01" name="manual_score" value="<?php echo esc_attr( $booking['manual_score'] ); ?>"></label></p><p><label>Interview <input type="number" step="0.01" name="interview_score" value="<?php echo esc_attr( $booking['interview_score'] ); ?>"></label></p><p>Total: <?php echo esc_html( $booking['total_score'] ); ?></p><?php submit_button( 'Оновити scores', 'secondary', '', false ); ?></form></div>
        <div class="ucu-admin-panel ucu-admin-panel--wide"><h2>Усі відповіді</h2><table class="widefat striped"><tbody><?php foreach ( UCU_Collegium_Form_Fields::get_fields() as $field ) : ?><?php if ( 'attachment' === $field['type'] ) { continue; } ?><tr><th><?php echo esc_html( $field['label'] ); ?></th><td><?php echo esc_html( UCU_Collegium_Form_Fields::format_value( $field, $booking['form_data_array'][ $field['key'] ] ?? '' ) ); ?></td></tr><?php endforeach; ?></tbody></table></div>
        <div class="ucu-admin-panel ucu-admin-panel--wide"><h2>Дії</h2>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block;margin-right:8px;"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="cancel"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><?php submit_button( 'Скасувати заявку', 'delete', '', false ); ?></form>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block;margin-right:8px;"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="retry_calendar"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><?php submit_button( 'Retry Calendar/Meet', 'secondary', '', false ); ?></form>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block;margin-right:8px;"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="retry_sheets"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><?php submit_button( 'Retry Sheets sync', 'secondary', '', false ); ?></form>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block;margin-right:8px;"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="resend_user"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><?php submit_button( 'Resend user email', 'secondary', '', false ); ?></form>
            <form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="display:inline-block;margin-right:8px;"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="resend_admin"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><?php submit_button( 'Resend admin email', 'secondary', '', false ); ?></form>
            <hr><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ucu_collegium_booking_action"><input type="hidden" name="do" value="move"><input type="hidden" name="booking_id" value="<?php echo (int) $booking['id']; ?>"><?php wp_nonce_field( 'ucu_collegium_booking_action' ); ?><label>Перенести на інший слот <select name="new_slot_id"><?php foreach ( $available_slots as $available_slot ) : ?><option value="<?php echo (int) $available_slot['id']; ?>"><?php echo esc_html( $available_slot['slot_date'] . ' ' . substr( $available_slot['start_time'], 0, 5 ) . '-' . substr( $available_slot['end_time'], 0, 5 ) ); ?></option><?php endforeach; ?></select></label> <?php submit_button( 'Перенести', 'secondary', '', false ); ?></form>
            <p><a class="button" href="<?php echo esc_url( wp_nonce_url( admin_url( 'admin-post.php?action=ucu_collegium_export_csv' ), 'ucu_collegium_export_csv' ) ); ?>">Export CSV</a></p>
        </div>
    </div>
</div>
